version: 2

updates:
  - package-ecosystem: 'maven'
    directory: '/artifacts'
    registries:
      - maven-github
    schedule:
      interval: 'daily'

registries:
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/ecristobal/borealis-parent
    username: ecristobal
    password: ${{ secrets.MAVEN_TOKEN }}