name: Build Maven artifacts

on:
  workflow_call:
    inputs:
      domain:
        required: true
        type: string

jobs:
  build-artifact:
    name: Build Borealis Data Platform artifacts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: artifacts/${{ inputs.domain }}
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.5.1
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build artifacts
        run: ./mvnw -B clean verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Checkstyle analysis
        run: ./mvnw -B checkstyle:checkstyle

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-maven
          restore-keys: ${{ runner.os }}-sonar-maven

      - name: Run SonarCloud analysis
        run: |
          ./mvnw -B sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=ecristobal \
          -Dsonar.projectKey=ecristobal_borealis-data-platform-${{ inputs.domain }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
