name: Build Maven artifacts

on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - main
    paths:
      - 'artifacts/**'
      - '.github/workflows/build-artifacts.yml'
  pull_request:
    paths:
      - 'artifacts/**'
      - '.github/workflows/build-artifacts.yml'

jobs:
  build-artifact:
    name: Build Borealis Data Platform artifacts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: artifacts
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build artifacts
        run: ./mvnw -B clean verify
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Checkstyle analysis
        run: ./mvnw -B checkstyle:checkstyle

      - name: Run SonarCloud analysis
        run: ./mvnw -B sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=ecristobal \
          -Dsonar.projectKey=ecristobal_borealis-data-platform
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
