name: 'Build Borealis Data Platform GCP infrastructure'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'infrastructure/gcp/**'
      - '.github/workflows/build-terraform.yml'
      - '.github/workflows/build-gcp-infra.yml'
  pull_request:
    paths:
      - 'infrastructure/gcp/**'
      - '.github/workflows/build-terraform.yml'
      - '.github/workflows/build-gcp-infra.yml'

permissions:
  contents: read
  security-events: write

jobs:
  build-gcp-infra-staging:
    name: 'Build GCP infrastructure in staging'
    uses: ecristobal/borealis-data-platform/.github/workflows/build-terraform.yml@main
    with:
      domain: gcp
      terraform-organization: borealis-infrastructure
      terraform-workspace: borealis-data-platform-gcp-staging
    secrets: inherit
