name: 'Build Borealis Data Platform infrastructure in staging'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'infrastructure/**.tf'
      - '.github/workflows/build-infrastructure.yml'
  pull_request:
    paths:
      - 'infrastructure/**.tf'
      - '.github/workflows/build-infrastructure.yml'

permissions:
  contents: read
  security-events: write

jobs:
  build-infrastructure-staging:
    name: 'Build infrastructure in staging'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: infrastructure

    env:
      TF_CLOUD_ORGANIZATION: borealis-infrastructure
      TF_WORKSPACE: borealis-gcp-data-platform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Snyk analysis
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: infrastructure/main.tf

      - name: Upload Snyk analysis to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      - name: Terraform plan
        run: terraform plan -input=false

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
