name: 'Build Borealis Data Platform infrastructure in staging'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'infrastructure/**'
      - '.github/workflows/build-infrastructure.yml'
  pull_request:
    paths:
      - 'infrastructure/**'
      - '.github/workflows/build-infrastructure.yml'

permissions:
  contents: read
  security-events: write

jobs:
  build-infrastructure-staging:
    name: 'Build infrastructure in staging'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: infrastructure

    env:
      TF_CLOUD_ORGANIZATION: borealis-infrastructure
      TF_WORKSPACE: borealis-data-platform-gcp-staging

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-infra
          restore-keys: ${{ runner.os }}-sonar-infra

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@master
        with:
          fetch-depth: 0
          projectBaseDir: infrastructure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Snyk analysis
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: infrastructure/main.tf

      - name: Terraform plan
        run: terraform plan -input=false

      - name: Terraform apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
