name: Build Maven artifacts

on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - main
    paths:
      - 'artifacts/**'
      - '.github/workflows/build-artifacts.yml'
  pull_request:
    paths:
      - 'artifacts/**'
      - '.github/workflows/build-artifacts.yml'

jobs:
  build-artifact:
    name: Build Borealis Data Platform artifacts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: artifacts
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build artifact
        run: ./mvnw -B clean verify

#      - name: Upload vulnerability scan results to GitHub Code Scanning
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: artifacts/snyk.sarif
