name: Deploy Maven artifacts

on:
  release:
    types: [ published ]
  push:
    branches:
      - main

jobs:
  build-release:
    name: Deploy Borealis Data Platform artifacts
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: artifacts
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build & Deploy release
        run: ./mvnw -B deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run SonarCloud analysis
        run: ./mvnw sonar:sonar

  check-vulnerabilities:
    name: Check vulnerabilities with Snyk
    uses: ecristobal/borealis-parent/.github/workflows/check-vulnerabilities.yml@main
    secrets: inherit
    defaults:
      run:
        working-directory: artifacts

  delete-versions:
    needs: build-release
    name: Delete old artifact versions from artifact repository
    runs-on: ubuntu-latest
    steps:
      - name: Remove old parent artifact versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.daycare.center.data-platform-artifacts'
          min-versions-to-keep: 4
      - name: Remove old ingestion artifact versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.daycare.center.ingestion'
          min-versions-to-keep: 4
      - name: Remove old storage artifact versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.daycare.center.storage'
          min-versions-to-keep: 4