name: Deploy Maven artifacts for Exercises

on:
  release:
    types: [ published ]
  push:
    branches:
      - main
    paths:
      - 'artifacts/exercises/**'
      - '.github/workflows/deploy-artifacts.yml'
      - '.github/workflows/deploy-exercises-artifacts.yml'

jobs:
  deploy-artifacts:
    name: Deploy Borealis Data Platform artifacts for Exercises
    uses: ecristobal/borealis-data-platform/.github/workflows/deploy-artifacts.yml@main
    with:
      domain: exercises
    secrets: inherit

  delete-versions:
    needs: deploy-artifacts
    name: Delete old artifact versions from artifact repository
    runs-on: ubuntu-latest
    steps:
      - name: Remove old parent artifact versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.daycare.center.data.platform.exercises.parent'
          min-versions-to-keep: 4

      - name: Remove old parent artifact versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.daycare.center.data.platform.exercises.schemas.parent'
          min-versions-to-keep: 4

      - name: Remove old parent artifact versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.daycare.center.data.platform.exercises.schemas.json'
          min-versions-to-keep: 4

      - name: Remove old parent artifact versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.daycare.center.data.platform.exercises.schemas.avro'
          min-versions-to-keep: 4

      - name: Remove old parent artifact versions
        uses: actions/delete-package-versions@v3
        with:
          package-name: 'es.borealis.daycare.center.data.platform.exercises.schemas.parquet'
          min-versions-to-keep: 4